batch_size: 8
fft_length: 384
frame_length: 256
frame_step: 160
input_shape:
- 1392
- 193
learning_rate: 0.0005
max_spectrogram_length: 1392
max_text_length: 170
model_path: Models/Trained Model\202402230111
train_epochs: 1000
train_workers: 20
vocab: 'abcdefghijklmnopqrstuvwxyz''?! '
