batch_size: 8
fft_length: 384
frame_length: 256
frame_step: 160
input_shape: null
learning_rate: 0.0005
max_spectrogram_length: null
max_text_length: null
model_path: Models/Trained Model\202402230058
train_epochs: 1000
train_workers: 20
vocab: 'abcdefghijklmnopqrstuvwxyz''?! '
